#!/usr/bin/env python3
"""Instalador local de segredos do YBY.

Uso seguro:
  python3 core/install_secrets.py

Cole as chaves no terminal local, finalize com Ctrl+D.
O script grava `.env` e `backend/.env` com permissao 0600 e nunca imprime valores.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ROOT_ENV = ROOT / ".env"
BACKEND_ENV = ROOT / "backend" / ".env"

ALIASES = {
    "openrouter": "OPENROUTER_API_KEY",
    "openrouter_api_key": "OPENROUTER_API_KEY",
    "groq_api_key": "GROQ_API_KEY",
    "gemini_api_key": "GEMINI_API_KEY",
    "perplexity_api_key": "PERPLEXITY_API_KEY",
    "openai_api_key": "OPENAI_API_KEY",
    "deepseek_api_key": "DEEPSEEK_API_KEY",
    "ollama_host": "OLLAMA_HOST",
}

ORDER = [
    "GEMINI_API_KEY",
    "GROQ_API_KEY",
    "OPENROUTER_API_KEY",
    "OPENAI_API_KEY",
    "DEEPSEEK_API_KEY",
    "PERPLEXITY_API_KEY",
    "OLLAMA_HOST",
    "APP_URL",
    "APP_ENV",
]

DEFAULTS = {
    "OLLAMA_HOST": "http://127.0.0.1:11434",
    "APP_URL": "http://localhost:3000",
    "APP_ENV": "development",
}


def normalize_key(raw_key: str) -> str | None:
    key = raw_key.strip().lower().replace("-", "_").replace(" ", "_")
    return ALIASES.get(key)


def parse_lines(text: str) -> dict[str, str]:
    secrets: dict[str, str] = {}
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        if "=" in line:
            raw_key, value = line.split("=", 1)
        elif ":" in line:
            raw_key, value = line.split(":", 1)
        else:
            continue

        key = normalize_key(raw_key)
        value = value.strip().strip("\"'")
        if key and value:
            secrets[key] = value

    return secrets


def read_existing(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip("\"'")
    return values


def quote_env(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_env(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# YBY local secrets. Generated by core/install_secrets.py.",
        "# Never commit this file.",
        "",
    ]
    for key in ORDER:
        value = values.get(key, DEFAULTS.get(key, ""))
        lines.append(f"{key}={quote_env(value) if value else ''}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(path, 0o600)


def looks_like_real_secret(value: str) -> bool:
    return bool(re.search(r"[A-Za-z0-9_./+=-]{24,}", value))


def main() -> int:
    print("[YBY] Cole suas chaves agora. Finalize com Ctrl+D.")
    input_text = sys.stdin.read()
    parsed = parse_lines(input_text)
    if not parsed:
        print("[YBY] Nenhuma chave reconhecida. Nada foi gravado.")
        return 1

    existing = read_existing(ROOT_ENV)
    values = {**DEFAULTS, **existing, **parsed}
    write_env(ROOT_ENV, values)
    write_env(BACKEND_ENV, values)

    installed = [key for key in ORDER if key in parsed]
    weak = [key for key in installed if not looks_like_real_secret(parsed[key]) and key != "OLLAMA_HOST"]

    print(f"[YBY] Segredos instalados: {', '.join(installed)}")
    if weak:
        print(f"[YBY] Atencao: formato incomum em {', '.join(weak)}")
    print("[YBY] Arquivos atualizados: .env, backend/.env (0600)")
    print("[YBY] Proximo passo: python3 core/api_healthcheck.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
